/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/jaron/.choosenim/toolchains/nim-#devel/lib' -o /home/jaron/nimble-meta/src/nimcache/nimble_meta_nimble_meta.o /home/jaron/nimble-meta/src/nimcache/nimble_meta_nimble_meta.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g;
typedef struct tySequence_mv9agb2xdbok9bcyHb85sA7g tySequence_mv9agb2xdbok9bcyHb85sA7g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg;
typedef struct tyObject_Option_HEmqEHziDcvusZwdi0aAgw tyObject_Option_HEmqEHziDcvusZwdi0aAgw;
typedef struct tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw;
typedef struct RootObj RootObj;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
struct tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g {
tySequence_mv9agb2xdbok9bcyHb85sA7g* validationErrors;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg {
NI something;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg {
NimStringDesc* message;
};
struct tyObject_Option_HEmqEHziDcvusZwdi0aAgw {
tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg val;
NIM_BOOL has;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct RootObj {
TNimType* m_type;
};
struct tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw {
  RootObj Sup;
NimStringDesc* b;
NI a;
tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg c;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tySequence_mv9agb2xdbok9bcyHb85sA7g {
  TGenericSeq Sup;
  tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_KjYIujXXdOnppOXclnbEhA_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(void, validate_1gZiQh8gTMd3EpyGNxwhnQ)(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg t, tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, newErrorAccumulator_zE6wvS9c1yHtFSzvx5PJ9c4A)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result);
N_LIB_PRIVATE N_NIMCALL(void, addError_9arb632ZldByIqtgnGo8VQQ)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* self, tyObject_Option_HEmqEHziDcvusZwdi0aAgw error);
N_LIB_PRIVATE N_NIMCALL(void, lessThan_WzP5ji53B2xEnSFwA3ZWKQ)(NI field, NI x, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasErrors_ub2d2IRcx5CmCP3QXRTWaQ)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g accumulator);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__ac11YPZAKAZtFeskGmHFkw)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_NIMCALL(void, TM_KjYIujXXdOnppOXclnbEhA_4)(void);
N_LIB_PRIVATE N_NIMCALL(void, validate_6UhEUAACtsIHFyuddfmpcw)(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw* t, tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result);
N_LIB_PRIVATE N_NIMCALL(void, matchesPattern_BBbDuWiSk8X4oH9cFK9cs77Q)(NimStringDesc* field, NimStringDesc* pattern, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
N_LIB_PRIVATE N_NIMCALL(void, valid_W3dBE63L6n6Qz0IT19auaQA)(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg field, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
static N_NIMCALL(void, Marker_tyRef_HOKwk7FlaZxV5x7QiHn6VA)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseutilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parseutilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_bitopsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_bitopsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_mathInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_mathDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_algorithmInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_algorithmDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strutilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_strutilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_hashesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_hashesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_tablesInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_tablesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_streamsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_streamsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_lexbaseInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_lexbaseDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unicodeInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_unicodeDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_macrosInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_macrosDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parsejsonInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_parsejsonDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_typetraitsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_typetraitsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_optionsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_jsonInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_jsonDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_sequtilsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_sequtilsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_sugarInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_sugarDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_typeinfoInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_typeinfoDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_pcreInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_pcreDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_rtarraysInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_rtarraysDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_reInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, stdlib_reDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validator_defsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validator_defsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validatorsInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validatorsDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimble_metaDatInit000)(void);
tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g validation_71E2pixeN1yba62jbdArAA;
extern TNimType NTI_6Z5YAMO0m9c80IXA6xPB06g_;
extern TNimType NTI_mv9agb2xdbok9bcyHb85sA7g_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g errors_YxlBl448mHN9cPNGNWa4VqA;
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_HyLS6oFqBeEyQNmhr4osFw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_yBgcNnzhdxAjCT5OOPb9bVg_;
TNimType NTI_HOKwk7FlaZxV5x7QiHn6VA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NIM_CONST tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg TM_KjYIujXXdOnppOXclnbEhA_3 = {((NI) 20)};
STRING_LITERAL(TM_KjYIujXXdOnppOXclnbEhA_5, "hello|bye", 9);
STRING_LITERAL(TM_KjYIujXXdOnppOXclnbEhA_7, "slkjdf", 6);
static N_NIMCALL(void, TM_KjYIujXXdOnppOXclnbEhA_2)(void) {
	nimGCvisit((void*)validation_71E2pixeN1yba62jbdArAA.validationErrors, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, validate_1gZiQh8gTMd3EpyGNxwhnQ)(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg t, tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result) {
	tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g errors;
	tyObject_Option_HEmqEHziDcvusZwdi0aAgw T1_;
	nimfr_("validate", "validators.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6Z5YAMO0m9c80IXA6xPB06g_));
	nimln_(4, "nimble_meta.nim");
	memset((void*)(&errors), 0, sizeof(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g));
	nimln_(459, "macros.nim");
	newErrorAccumulator_zE6wvS9c1yHtFSzvx5PJ9c4A((&errors));
	nimln_(130, "validators.nim");
	nimln_(4, "nimble_meta.nim");
	memset((void*)(&T1_), 0, sizeof(tyObject_Option_HEmqEHziDcvusZwdi0aAgw));
	lessThan_WzP5ji53B2xEnSFwA3ZWKQ(t.something, ((NI) 50), (&T1_));
	addError_9arb632ZldByIqtgnGo8VQQ((&errors), T1_);
	genericSeqAssign((&(*Result).validationErrors), errors.validationErrors, (&NTI_mv9agb2xdbok9bcyHb85sA7g_));
	popFrame();
}
static N_NIMCALL(void, TM_KjYIujXXdOnppOXclnbEhA_4)(void) {
	nimGCvisit((void*)errors_YxlBl448mHN9cPNGNWa4VqA.validationErrors, 0);
}

N_LIB_PRIVATE N_NIMCALL(void, validate_6UhEUAACtsIHFyuddfmpcw)(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw* t, tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result) {
	tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g errors;
	tyObject_Option_HEmqEHziDcvusZwdi0aAgw T1_;
	tyObject_Option_HEmqEHziDcvusZwdi0aAgw T2_;
	tyObject_Option_HEmqEHziDcvusZwdi0aAgw T3_;
	nimfr_("validate", "validators.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6Z5YAMO0m9c80IXA6xPB06g_));
	nimln_(14, "nimble_meta.nim");
	memset((void*)(&errors), 0, sizeof(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g));
	nimln_(459, "macros.nim");
	newErrorAccumulator_zE6wvS9c1yHtFSzvx5PJ9c4A((&errors));
	nimln_(130, "validators.nim");
	nimln_(14, "nimble_meta.nim");
	memset((void*)(&T1_), 0, sizeof(tyObject_Option_HEmqEHziDcvusZwdi0aAgw));
	matchesPattern_BBbDuWiSk8X4oH9cFK9cs77Q((*t).b, ((NimStringDesc*) &TM_KjYIujXXdOnppOXclnbEhA_5), (&T1_));
	addError_9arb632ZldByIqtgnGo8VQQ((&errors), T1_);
	nimln_(130, "validators.nim");
	nimln_(14, "nimble_meta.nim");
	memset((void*)(&T2_), 0, sizeof(tyObject_Option_HEmqEHziDcvusZwdi0aAgw));
	lessThan_WzP5ji53B2xEnSFwA3ZWKQ((*t).a, ((NI) 5), (&T2_));
	addError_9arb632ZldByIqtgnGo8VQQ((&errors), T2_);
	nimln_(130, "validators.nim");
	nimln_(14, "nimble_meta.nim");
	memset((void*)(&T3_), 0, sizeof(tyObject_Option_HEmqEHziDcvusZwdi0aAgw));
	valid_W3dBE63L6n6Qz0IT19auaQA((*t).c, (&T3_));
	addError_9arb632ZldByIqtgnGo8VQQ((&errors), T3_);
	genericSeqAssign((&(*Result).validationErrors), errors.validationErrors, (&NTI_mv9agb2xdbok9bcyHb85sA7g_));
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_HOKwk7FlaZxV5x7QiHn6VA)(void* p, NI op) {
	tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw* a;
	a = (tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw*)p;
	nimGCvisit((void*)(*a).b, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_bitopsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_macrosDatInit000();
	stdlib_parsejsonDatInit000();
	stdlib_typetraitsDatInit000();
	stdlib_optionsDatInit000();
	stdlib_jsonDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_sugarDatInit000();
	stdlib_typeinfoDatInit000();
	stdlib_pcreDatInit000();
	stdlib_rtarraysDatInit000();
	stdlib_reDatInit000();
	nimble_meta_validator_defsDatInit000();
	nimble_meta_validatorsDatInit000();
	nimble_metaDatInit000();
	stdlib_parseutilsInit000();
	stdlib_bitopsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_macrosInit000();
	stdlib_parsejsonInit000();
	stdlib_typetraitsInit000();
	stdlib_optionsInit000();
	stdlib_jsonInit000();
	stdlib_sequtilsInit000();
	stdlib_sugarInit000();
	stdlib_typeinfoInit000();
	stdlib_pcreInit000();
	stdlib_rtarraysInit000();
	stdlib_reInit000();
	nimble_meta_validator_defsInit000();
	nimble_meta_validatorsInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
	tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw* T7_;
	NimStringDesc* T8_;
	nimfr_("nimble_meta", "nimble_meta.nim");
nimRegisterGlobalMarker(TM_KjYIujXXdOnppOXclnbEhA_2);
nimRegisterGlobalMarker(TM_KjYIujXXdOnppOXclnbEhA_4);
	nimln_(9, "nimble_meta.nim");
	validate_1gZiQh8gTMd3EpyGNxwhnQ(TM_KjYIujXXdOnppOXclnbEhA_3, (&validation_71E2pixeN1yba62jbdArAA));
	nimln_(10, "nimble_meta.nim");
	{
		NIM_BOOL T3_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = hasErrors_ub2d2IRcx5CmCP3QXRTWaQ(validation_71E2pixeN1yba62jbdArAA);
		if (!T3_) goto LA4_;
		nimln_(11, "nimble_meta.nim");
		memset((void*)T6_, 0, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		T6_[0] = dollar__ac11YPZAKAZtFeskGmHFkw(validation_71E2pixeN1yba62jbdArAA);
		echoBinSafe(T6_, 1);
	}
	LA4_: ;
	nimln_(21, "nimble_meta.nim");
	T7_ = (tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw*)0;
	T7_ = (tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw*) newObj((&NTI_HOKwk7FlaZxV5x7QiHn6VA_), sizeof(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw));
	(*T7_).Sup.m_type = (&NTI_HyLS6oFqBeEyQNmhr4osFw_);
	(*T7_).a = ((NI) 4);
	T8_ = (NimStringDesc*)0;
	T8_ = (*T7_).b; (*T7_).b = copyStringRC1(((NimStringDesc*) &TM_KjYIujXXdOnppOXclnbEhA_7));
	if (T8_) nimGCunrefNoCycle(T8_);
	chckNil((void*)(&(*T7_).c));
	genericReset((void*)(&(*T7_).c), (&NTI_yBgcNnzhdxAjCT5OOPb9bVg_));
	(*T7_).c.something = ((NI) 70);
	validate_6UhEUAACtsIHFyuddfmpcw(T7_, (&errors_YxlBl448mHN9cPNGNWa4VqA));
	nimln_(22, "nimble_meta.nim");
	{
		NIM_BOOL T11_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T14_;
		T11_ = (NIM_BOOL)0;
		T11_ = hasErrors_ub2d2IRcx5CmCP3QXRTWaQ(errors_YxlBl448mHN9cPNGNWa4VqA);
		if (!T11_) goto LA12_;
		nimln_(23, "nimble_meta.nim");
		memset((void*)T14_, 0, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		T14_[0] = dollar__ac11YPZAKAZtFeskGmHFkw(errors_YxlBl448mHN9cPNGNWa4VqA);
		echoBinSafe(T14_, 1);
	}
	LA12_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nimble_metaDatInit000)(void) {
static TNimNode* TM_KjYIujXXdOnppOXclnbEhA_6[3];
static TNimNode TM_KjYIujXXdOnppOXclnbEhA_0[5];
NTI_HyLS6oFqBeEyQNmhr4osFw_.size = sizeof(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw);
NTI_HyLS6oFqBeEyQNmhr4osFw_.kind = 17;
NTI_HyLS6oFqBeEyQNmhr4osFw_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_KjYIujXXdOnppOXclnbEhA_6[0] = &TM_KjYIujXXdOnppOXclnbEhA_0[1];
TM_KjYIujXXdOnppOXclnbEhA_0[1].kind = 1;
TM_KjYIujXXdOnppOXclnbEhA_0[1].offset = offsetof(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw, b);
TM_KjYIujXXdOnppOXclnbEhA_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_KjYIujXXdOnppOXclnbEhA_0[1].name = "b";
TM_KjYIujXXdOnppOXclnbEhA_6[1] = &TM_KjYIujXXdOnppOXclnbEhA_0[2];
TM_KjYIujXXdOnppOXclnbEhA_0[2].kind = 1;
TM_KjYIujXXdOnppOXclnbEhA_0[2].offset = offsetof(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw, a);
TM_KjYIujXXdOnppOXclnbEhA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_KjYIujXXdOnppOXclnbEhA_0[2].name = "a";
TM_KjYIujXXdOnppOXclnbEhA_6[2] = &TM_KjYIujXXdOnppOXclnbEhA_0[3];
NTI_yBgcNnzhdxAjCT5OOPb9bVg_.size = sizeof(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg);
NTI_yBgcNnzhdxAjCT5OOPb9bVg_.kind = 18;
NTI_yBgcNnzhdxAjCT5OOPb9bVg_.base = 0;
NTI_yBgcNnzhdxAjCT5OOPb9bVg_.flags = 3;
TM_KjYIujXXdOnppOXclnbEhA_0[4].kind = 1;
TM_KjYIujXXdOnppOXclnbEhA_0[4].offset = offsetof(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg, something);
TM_KjYIujXXdOnppOXclnbEhA_0[4].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_KjYIujXXdOnppOXclnbEhA_0[4].name = "something";
NTI_yBgcNnzhdxAjCT5OOPb9bVg_.node = &TM_KjYIujXXdOnppOXclnbEhA_0[4];
TM_KjYIujXXdOnppOXclnbEhA_0[3].kind = 1;
TM_KjYIujXXdOnppOXclnbEhA_0[3].offset = offsetof(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw, c);
TM_KjYIujXXdOnppOXclnbEhA_0[3].typ = (&NTI_yBgcNnzhdxAjCT5OOPb9bVg_);
TM_KjYIujXXdOnppOXclnbEhA_0[3].name = "c";
TM_KjYIujXXdOnppOXclnbEhA_0[0].len = 3; TM_KjYIujXXdOnppOXclnbEhA_0[0].kind = 2; TM_KjYIujXXdOnppOXclnbEhA_0[0].sons = &TM_KjYIujXXdOnppOXclnbEhA_6[0];
NTI_HyLS6oFqBeEyQNmhr4osFw_.node = &TM_KjYIujXXdOnppOXclnbEhA_0[0];
NTI_HOKwk7FlaZxV5x7QiHn6VA_.size = sizeof(tyObject_TestcolonObjectType__HyLS6oFqBeEyQNmhr4osFw*);
NTI_HOKwk7FlaZxV5x7QiHn6VA_.kind = 22;
NTI_HOKwk7FlaZxV5x7QiHn6VA_.base = (&NTI_HyLS6oFqBeEyQNmhr4osFw_);
NTI_HOKwk7FlaZxV5x7QiHn6VA_.marker = Marker_tyRef_HOKwk7FlaZxV5x7QiHn6VA;
}

