/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/jaron/.choosenim/toolchains/nim-#devel/lib' -o /home/jaron/nimble-meta/src/nimcache/nimble_meta_validators.o /home/jaron/nimble-meta/src/nimcache/nimble_meta_validators.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g;
typedef struct tySequence_mv9agb2xdbok9bcyHb85sA7g tySequence_mv9agb2xdbok9bcyHb85sA7g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Option_HEmqEHziDcvusZwdi0aAgw tyObject_Option_HEmqEHziDcvusZwdi0aAgw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg;
struct tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g {
tySequence_mv9agb2xdbok9bcyHb85sA7g* validationErrors;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg {
NimStringDesc* message;
};
struct tyObject_Option_HEmqEHziDcvusZwdi0aAgw {
tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg val;
NIM_BOOL has;
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg {
NI something;
};
typedef NimStringDesc* tyArray_sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tySequence_mv9agb2xdbok9bcyHb85sA7g {
  TGenericSeq Sup;
  tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_mv9agb2xdbok9bcyHb85sA7g)(void* p, NI op);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gjv3f9cQiUqZpcpOB2IVYzA)(tyObject_Option_HEmqEHziDcvusZwdi0aAgw self);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NIM_BOOL, isSome_iM0Qvrw9cbOk7N5anau1apAoptions)(tyObject_Option_HEmqEHziDcvusZwdi0aAgw self);
N_LIB_PRIVATE N_NIMCALL(void, get_ErstGCbnxlUul7eGCCjFWw)(tyObject_Option_HEmqEHziDcvusZwdi0aAgw self, tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg* Result);
N_NIMCALL(TGenericSeq*, incrSeqV3)(TGenericSeq* s, TNimType* typ);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, validate_1gZiQh8gTMd3EpyGNxwhnQ)(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg t, tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__gn5RDJwdxOCqUrZsyeCxWw)(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__WHll9bh3rqqajAktDjPkxww)(tySequence_mv9agb2xdbok9bcyHb85sA7g* x);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasErrors_ub2d2IRcx5CmCP3QXRTWaQ)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g accumulator);
N_LIB_PRIVATE N_NIMCALL(void, someValidationError_ImxUrC4nms9cH9c8ChVHzBvw)(NimStringDesc* errorString, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatVarargs)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(void, none_cbiu6X7z5hI5dRoRx6mN4g)(tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
TNimType NTI_6Z5YAMO0m9c80IXA6xPB06g_;
extern TNimType NTI_aXnTBPeyi88c39aD8TIHWFg_;
TNimType NTI_mv9agb2xdbok9bcyHb85sA7g_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_HEmqEHziDcvusZwdi0aAgw_;
STRING_LITERAL(TM_KX02bSj4vJttHkstkg4kAA_2, "ERROR: ", 7);
STRING_LITERAL(TM_KX02bSj4vJttHkstkg4kAA_4, "ADding to my validation errors", 30);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_KX02bSj4vJttHkstkg4kAA_3 = {((NimStringDesc*) &TM_KX02bSj4vJttHkstkg4kAA_4)}
;
STRING_LITERAL(TM_KX02bSj4vJttHkstkg4kAA_5, "Validating inner object, field: ", 32);
STRING_LITERAL(TM_KX02bSj4vJttHkstkg4kAA_6, "v: ", 3);
STRING_LITERAL(TM_KX02bSj4vJttHkstkg4kAA_8, "inner object has errors", 23);
NIM_CONST tyArray_nHXaesL0DJZHyVS07ARPRA TM_KX02bSj4vJttHkstkg4kAA_7 = {((NimStringDesc*) &TM_KX02bSj4vJttHkstkg4kAA_8)}
;
STRING_LITERAL(TM_KX02bSj4vJttHkstkg4kAA_9, "Nested object had validation errors $1", 38);
static N_NIMCALL(void, Marker_tySequence_mv9agb2xdbok9bcyHb85sA7g)(void* p, NI op) {
	tySequence_mv9agb2xdbok9bcyHb85sA7g* a;
	NI T1_;
	a = (tySequence_mv9agb2xdbok9bcyHb85sA7g*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].message, op);
	}
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, newErrorAccumulator_zE6wvS9c1yHtFSzvx5PJ9c4A)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* Result) {
	nimfr_("newErrorAccumulator", "validators.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6Z5YAMO0m9c80IXA6xPB06g_));
	nimln_(15, "validators.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_6Z5YAMO0m9c80IXA6xPB06g_));
	unsureAsgnRef((void**) (&(*Result).validationErrors), (tySequence_mv9agb2xdbok9bcyHb85sA7g*) newSeq((&NTI_mv9agb2xdbok9bcyHb85sA7g_), 0));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, isSome_iM0Qvrw9cbOk7N5anau1apAoptions)(tyObject_Option_HEmqEHziDcvusZwdi0aAgw self) {
	NIM_BOOL result;
	nimfr_("isSome", "options.nim");
	result = (NIM_BOOL)0;
	nimln_(115, "options.nim");
	result = self.has;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, addError_9arb632ZldByIqtgnGo8VQQ)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g* self, tyObject_Option_HEmqEHziDcvusZwdi0aAgw error) {
	tyArray_Re75IspeoxXy2oCZHwcRrA T1_;
	nimfr_("addError", "validators.nim");
	nimln_(18, "validators.nim");
	memset((void*)T1_, 0, sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA));
	T1_[0] = copyString(((NimStringDesc*) &TM_KX02bSj4vJttHkstkg4kAA_2));
	T1_[1] = dollar__gjv3f9cQiUqZpcpOB2IVYzA(error);
	echoBinSafe(T1_, 2);
	nimln_(20, "validators.nim");
	{
		NIM_BOOL T4_;
		tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg T7_;
		NI T8_;
		NimStringDesc* T9_;
		T4_ = (NIM_BOOL)0;
		T4_ = isSome_iM0Qvrw9cbOk7N5anau1apAoptions(error);
		if (!T4_) goto LA5_;
		nimln_(21, "validators.nim");
		echoBinSafe(TM_KX02bSj4vJttHkstkg4kAA_3, 1);
		nimln_(22, "validators.nim");
		memset((void*)(&T7_), 0, sizeof(tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg));
		get_ErstGCbnxlUul7eGCCjFWw(error, (&T7_));
		(*self).validationErrors = (tySequence_mv9agb2xdbok9bcyHb85sA7g*) incrSeqV3(&((*self).validationErrors)->Sup, (&NTI_mv9agb2xdbok9bcyHb85sA7g_));
		T8_ = (*self).validationErrors->Sup.len++;
		T9_ = (NimStringDesc*)0;
		T9_ = (*self).validationErrors->data[T8_].message; (*self).validationErrors->data[T8_].message = copyStringRC1(T7_.message);
		if (T9_) nimGCunrefNoCycle(T9_);
	}
	LA5_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasErrors_ub2d2IRcx5CmCP3QXRTWaQ)(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g accumulator) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("hasErrors", "validators.nim");
	result = (NIM_BOOL)0;
	nimln_(24, "validators.nim");
	T1_ = (accumulator.validationErrors ? accumulator.validationErrors->Sup.len : 0);
	result = (((NI) 0) < T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, valid_W3dBE63L6n6Qz0IT19auaQA)(tyObject_InnerObject_yBgcNnzhdxAjCT5OOPb9bVg field, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result) {
	tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g validation;
	tyArray_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	nimfr_("valid", "validators.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_HEmqEHziDcvusZwdi0aAgw_));
	memset((void*)(&validation), 0, sizeof(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g));
	nimln_(155, "validators.nim");
	validate_1gZiQh8gTMd3EpyGNxwhnQ(field, (&validation));
	nimln_(156, "validators.nim");
	memset((void*)T1_, 0, sizeof(tyArray_sMpvt1sOxOJ3LFGulnbeMQ));
	T1_[0] = copyString(((NimStringDesc*) &TM_KX02bSj4vJttHkstkg4kAA_5));
	T1_[1] = dollar__gn5RDJwdxOCqUrZsyeCxWw(field);
	T1_[2] = copyString(((NimStringDesc*) &TM_KX02bSj4vJttHkstkg4kAA_6));
	T1_[3] = dollar__WHll9bh3rqqajAktDjPkxww(validation.validationErrors);
	echoBinSafe(T1_, 4);
	nimln_(157, "validators.nim");
	{
		NIM_BOOL T4_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T7_;
		NimStringDesc* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = hasErrors_ub2d2IRcx5CmCP3QXRTWaQ(validation);
		if (!T4_) goto LA5_;
		nimln_(158, "validators.nim");
		echoBinSafe(TM_KX02bSj4vJttHkstkg4kAA_7, 1);
		nimln_(159, "validators.nim");
		memset((void*)T7_, 0, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		T7_[0] = dollar__gn5RDJwdxOCqUrZsyeCxWw(field);
		T8_ = (NimStringDesc*)0;
		T8_ = nsuFormatVarargs(((NimStringDesc*) &TM_KX02bSj4vJttHkstkg4kAA_9), T7_, 1);
		someValidationError_ImxUrC4nms9cH9c8ChVHzBvw(T8_, Result);
		goto BeforeRet_;
	}
	goto LA2_;
	LA5_: ;
	{
		nimln_(160, "validators.nim");
		none_cbiu6X7z5hI5dRoRx6mN4g(Result);
		goto BeforeRet_;
	}
	LA2_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validatorsInit000)(void) {
	nimfr_("validators", "validators.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validatorsDatInit000)(void) {
static TNimNode TM_KX02bSj4vJttHkstkg4kAA_0[1];
NTI_6Z5YAMO0m9c80IXA6xPB06g_.size = sizeof(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g);
NTI_6Z5YAMO0m9c80IXA6xPB06g_.kind = 18;
NTI_6Z5YAMO0m9c80IXA6xPB06g_.base = 0;
NTI_6Z5YAMO0m9c80IXA6xPB06g_.flags = 2;
NTI_mv9agb2xdbok9bcyHb85sA7g_.size = sizeof(tySequence_mv9agb2xdbok9bcyHb85sA7g*);
NTI_mv9agb2xdbok9bcyHb85sA7g_.kind = 24;
NTI_mv9agb2xdbok9bcyHb85sA7g_.base = (&NTI_aXnTBPeyi88c39aD8TIHWFg_);
NTI_mv9agb2xdbok9bcyHb85sA7g_.flags = 2;
NTI_mv9agb2xdbok9bcyHb85sA7g_.marker = Marker_tySequence_mv9agb2xdbok9bcyHb85sA7g;
TM_KX02bSj4vJttHkstkg4kAA_0[0].kind = 1;
TM_KX02bSj4vJttHkstkg4kAA_0[0].offset = offsetof(tyObject_ErrorAccumulator_6Z5YAMO0m9c80IXA6xPB06g, validationErrors);
TM_KX02bSj4vJttHkstkg4kAA_0[0].typ = (&NTI_mv9agb2xdbok9bcyHb85sA7g_);
TM_KX02bSj4vJttHkstkg4kAA_0[0].name = "validationErrors";
NTI_6Z5YAMO0m9c80IXA6xPB06g_.node = &TM_KX02bSj4vJttHkstkg4kAA_0[0];
}

