/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/jaron/.choosenim/toolchains/nim-#devel/lib' -o /home/jaron/nimble-meta/src/nimcache/nimble_meta_validator_defs.o /home/jaron/nimble-meta/src/nimcache/nimble_meta_validator_defs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Option_HEmqEHziDcvusZwdi0aAgw tyObject_Option_HEmqEHziDcvusZwdi0aAgw;
typedef struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg {
NimStringDesc* message;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NimStringDesc* tyArray_sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_Option_HEmqEHziDcvusZwdi0aAgw {
tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg val;
NIM_BOOL has;
};
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, someValidationError_ImxUrC4nms9cH9c8ChVHzBvw)(NimStringDesc* errorString, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
N_LIB_PRIVATE N_NIMCALL(void, some_WDskkjvG7OojJSkqbohGOQ)(tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg val, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatVarargs)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(void, none_cbiu6X7z5hI5dRoRx6mN4g)(tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result);
static N_INLINE(NIM_BOOL, match_y7rJUCS8uxf8NYoExwh5sAvalidator_defs)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
static N_INLINE(NI, matchLen_8tsep9b9cDFrTyTR0WU8CZogvalidator_defs)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(int, matchOrFind_lYP9aKTHndN56JtpfLZGvIg)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg flags);
TNimType NTI_aXnTBPeyi88c39aD8TIHWFg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_HEmqEHziDcvusZwdi0aAgw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_7mfsBH5TN4rx8OVJLPIH9aw_2, "lessThan: ", 10);
STRING_LITERAL(TM_7mfsBH5TN4rx8OVJLPIH9aw_3, "<", 1);
STRING_LITERAL(TM_7mfsBH5TN4rx8OVJLPIH9aw_4, "$1 was not less than $2", 23);
STRING_LITERAL(TM_7mfsBH5TN4rx8OVJLPIH9aw_5, "$1 does not match pattern", 25);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, someValidationError_ImxUrC4nms9cH9c8ChVHzBvw)(NimStringDesc* errorString, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result) {
	tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg T1_;
	nimfr_("someValidationError", "validator_defs.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_HEmqEHziDcvusZwdi0aAgw_));
	nimln_(9, "validator_defs.nim");
	memset((void*)(&T1_), 0, sizeof(tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg));
	memset((void*)(&T1_), 0, sizeof(tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg));
	T1_.message = copyString(errorString);
	some_WDskkjvG7OojJSkqbohGOQ(T1_, Result);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, lessThan_WzP5ji53B2xEnSFwA3ZWKQ)(NI field, NI x, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result) {
	tyArray_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	nimfr_("lessThan", "validator_defs.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_HEmqEHziDcvusZwdi0aAgw_));
	nimln_(21, "validator_defs.nim");
	memset((void*)T1_, 0, sizeof(tyArray_sMpvt1sOxOJ3LFGulnbeMQ));
	T1_[0] = copyString(((NimStringDesc*) &TM_7mfsBH5TN4rx8OVJLPIH9aw_2));
	T1_[1] = nimIntToStr(field);
	T1_[2] = copyString(((NimStringDesc*) &TM_7mfsBH5TN4rx8OVJLPIH9aw_3));
	T1_[3] = nimIntToStr(x);
	echoBinSafe(T1_, 4);
	nimln_(22, "validator_defs.nim");
	{
		tyArray_Re75IspeoxXy2oCZHwcRrA T6_;
		NimStringDesc* T7_;
		if (!!((field < x))) goto LA4_;
		nimln_(23, "validator_defs.nim");
		memset((void*)T6_, 0, sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA));
		T6_[0] = nimIntToStr(field);
		T6_[1] = nimIntToStr(x);
		T7_ = (NimStringDesc*)0;
		T7_ = nsuFormatVarargs(((NimStringDesc*) &TM_7mfsBH5TN4rx8OVJLPIH9aw_4), T6_, 2);
		someValidationError_ImxUrC4nms9cH9c8ChVHzBvw(T7_, Result);
		goto BeforeRet_;
	}
	goto LA2_;
	LA4_: ;
	{
		nimln_(24, "validator_defs.nim");
		none_cbiu6X7z5hI5dRoRx6mN4g(Result);
		goto BeforeRet_;
	}
	LA2_: ;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, matchLen_8tsep9b9cDFrTyTR0WU8CZogvalidator_defs)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim");
	result = (NI)0;
	nimln_(243, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_lYP9aKTHndN56JtpfLZGvIg(buf, pattern, ((NI) (((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))))), bufSize, ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, match_y7rJUCS8uxf8NYoExwh5sAvalidator_defs)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("match", "re.nim");
	result = (NIM_BOOL)0;
	nimln_(247, "re.nim");
	nimln_(400, "system.nim");
	nimln_(247, "re.nim");
	T1_ = (NI)0;
	T1_ = matchLen_8tsep9b9cDFrTyTR0WU8CZogvalidator_defs((s ? s->data : (NCSTRING)""), pattern, start, (s ? s->Sup.len : 0));
	result = !((T1_ == ((NI) -1)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, matchesPattern_BBbDuWiSk8X4oH9cFK9cs77Q)(NimStringDesc* field, NimStringDesc* pattern, tyObject_Option_HEmqEHziDcvusZwdi0aAgw* Result) {
	nimfr_("matchesPattern", "validator_defs.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_HEmqEHziDcvusZwdi0aAgw_));
	nimln_(29, "validator_defs.nim");
	{
		tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* T3_;
		NIM_BOOL T4_;
		tyArray_nHXaesL0DJZHyVS07ARPRA T7_;
		NimStringDesc* T8_;
		T3_ = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
		T3_ = re_2TnOqvPvxix6tRYnuIeq9bw(pattern, 16);
		T4_ = (NIM_BOOL)0;
		T4_ = match_y7rJUCS8uxf8NYoExwh5sAvalidator_defs(field, T3_, ((NI) 0));
		if (!!(T4_)) goto LA5_;
		nimln_(30, "validator_defs.nim");
		memset((void*)T7_, 0, sizeof(tyArray_nHXaesL0DJZHyVS07ARPRA));
		T7_[0] = copyString(field);
		T8_ = (NimStringDesc*)0;
		T8_ = nsuFormatVarargs(((NimStringDesc*) &TM_7mfsBH5TN4rx8OVJLPIH9aw_5), T7_, 1);
		someValidationError_ImxUrC4nms9cH9c8ChVHzBvw(T8_, Result);
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		nimln_(31, "validator_defs.nim");
		none_cbiu6X7z5hI5dRoRx6mN4g(Result);
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validator_defsInit000)(void) {
	nimfr_("validator_defs", "validator_defs.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, nimble_meta_validator_defsDatInit000)(void) {
static TNimNode TM_7mfsBH5TN4rx8OVJLPIH9aw_0[1];
NTI_aXnTBPeyi88c39aD8TIHWFg_.size = sizeof(tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg);
NTI_aXnTBPeyi88c39aD8TIHWFg_.kind = 18;
NTI_aXnTBPeyi88c39aD8TIHWFg_.base = 0;
NTI_aXnTBPeyi88c39aD8TIHWFg_.flags = 2;
TM_7mfsBH5TN4rx8OVJLPIH9aw_0[0].kind = 1;
TM_7mfsBH5TN4rx8OVJLPIH9aw_0[0].offset = offsetof(tyObject_ValidationError_aXnTBPeyi88c39aD8TIHWFg, message);
TM_7mfsBH5TN4rx8OVJLPIH9aw_0[0].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_7mfsBH5TN4rx8OVJLPIH9aw_0[0].name = "message";
NTI_aXnTBPeyi88c39aD8TIHWFg_.node = &TM_7mfsBH5TN4rx8OVJLPIH9aw_0[0];
}

