/* Generated by Nim Compiler v0.18.1 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I'/home/jaron/.choosenim/toolchains/nim-#devel/lib' -o /home/jaron/nimble-meta/src/nimcache/stdlib_re.o /home/jaron/nimble-meta/src/nimcache/stdlib_re.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ;
typedef struct tySequence_9apztJSmgERYU8fZOjI4pOg tySequence_9apztJSmgERYU8fZOjI4pOg;
typedef struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef int tyArray_hlIpJIfs8ECqDyETXoMStg[10];
struct tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ {
NI L;
tySequence_9apztJSmgERYU8fZOjI4pOg* spart;
tyArray_hlIpJIfs8ECqDyETXoMStg apart;
};
typedef N_CDECL_PTR(int, tyProc_y4Iy0gL1MDnSGVt43uUAgQ) (tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* code, tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* extra, NCSTRING subject, int length, int startoffset, int options, int* ovector, int ovecsize);
struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw {
tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* h;
tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* e;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
typedef N_CDECL_PTR(void, tyProc_5cp59bim9aJ4WupX5aVaD1Sg) (NCSTRING stringptr);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, tyProc_OMNNRjh8IIE9bAc9btZcg0NA) (NCSTRING pattern, int options, NCSTRING* errptr, int* erroffset, void* tableptr);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
NU raise_id;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
typedef N_CDECL_PTR(int, tyProc_KqPl2ltkjnSoyb04zAVCAQ) (int what, void* where);
typedef N_CDECL_PTR(tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ*, tyProc_qU2uMIyWirSwn1Nd4hJjDw) (tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* code, int options, NCSTRING* errptr);
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence_9apztJSmgERYU8fZOjI4pOg {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, initRtArray_BEO9bqjB0QqvrdxOQ9azwanw)(NI len, tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ* Result);
N_LIB_PRIVATE N_NIMCALL(int*, getRawData_BTVYxgjgdiz9c1Ui1wRvN6g)(tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ* x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, finalizeRegEx_00ANangMP3AvVFMngMDJRQ)(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* x);
static N_NIMCALL(void, Marker_tyRef_dkhOdInu11QXB2HnNpgmJQ)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, rawCompile_haWBfS5PJ5KixJQ9ccC8t5Q)(NimStringDesc* pattern, int flags);
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q)(NimStringDesc* msg) __attribute__((noreturn));
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_TzXIVAyhJcYnc0aWQVu3gg)(void* p, NI op);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c, NI count);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
extern tyProc_y4Iy0gL1MDnSGVt43uUAgQ Dl_276076_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_5cp59bim9aJ4WupX5aVaD1Sg Dl_276104_;
TNimType NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_;
extern TNimType NTI_WH9aVfHDhtZbU6Y5QgauqZQ_;
extern TNimType NTI_z1uZWlkSdiDfd9ahW9a6Ibug_;
TNimType NTI_dkhOdInu11QXB2HnNpgmJQ_;
extern tyProc_OMNNRjh8IIE9bAc9btZcg0NA Dl_276014_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_umh9boX2MJLOyMwHcR9cwMtQ_;
TNimType NTI_TzXIVAyhJcYnc0aWQVu3gg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_KqPl2ltkjnSoyb04zAVCAQ Dl_276036_;
extern tyProc_qU2uMIyWirSwn1Nd4hJjDw Dl_276163_;
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_4, "\012", 1);
STRING_LITERAL(TM_EFUBs0zJOEvQ2SEKsixA2w_5, "^\012", 2);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(int, matchOrFind_lYP9aKTHndN56JtpfLZGvIg)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags) {
	int result;
	tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ rtarray;
	int* rawMatches;
	nimfr_("matchOrFind", "re.nim");
	result = (int)0;
	memset((void*)(&rtarray), 0, sizeof(tyObject_RtArray_gCKWFhLtuzYY1Ki6cuwEPQ));
	nimln_(205, "re.nim");
	initRtArray_BEO9bqjB0QqvrdxOQ9azwanw(((NI) 3), (&rtarray));
	nimln_(206, "re.nim");
	rawMatches = getRawData_BTVYxgjgdiz9c1Ui1wRvN6g((&rtarray));
	nimln_(207, "re.nim");
	result = Dl_276076_((*pattern).h, (*pattern).e, buf, ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), flags, ((int*) (rawMatches)), ((int) 3));
	nimln_(209, "re.nim");
	{
		NI TM_EFUBs0zJOEvQ2SEKsixA2w_2;
		if (!(((NI32) 0) <= result)) goto LA3_;
		nimln_(210, "re.nim");
		TM_EFUBs0zJOEvQ2SEKsixA2w_2 = subInt(rawMatches[(((NI) 1))- 0], rawMatches[(((NI) 0))- 0]);
		if (TM_EFUBs0zJOEvQ2SEKsixA2w_2 < (-2147483647 -1) || TM_EFUBs0zJOEvQ2SEKsixA2w_2 > 2147483647) raiseOverflow();
		result = (NI32)(TM_EFUBs0zJOEvQ2SEKsixA2w_2);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, finalizeRegEx_00ANangMP3AvVFMngMDJRQ)(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* x) {
	nimfr_("finalizeRegEx", "re.nim");
	nimln_(66, "re.nim");
	Dl_276104_(((NCSTRING) ((*x).h)));
	nimln_(67, "re.nim");
	{
		if (!!(((*x).e == 0))) goto LA3_;
		nimln_(68, "re.nim");
		Dl_276104_(((NCSTRING) ((*x).e)));
	}
	LA3_: ;
	popFrame();
}
static N_NIMCALL(void, Marker_tyRef_dkhOdInu11QXB2HnNpgmJQ)(void* p, NI op) {
	tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* a;
	a = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)p;
}
static N_NIMCALL(void, Marker_tyRef_TzXIVAyhJcYnc0aWQVu3gg)(void* p, NI op) {
	tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ* a;
	a = (tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q)(NimStringDesc* msg) {
	tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ* e;
	NimStringDesc* T1_;
	nimfr_("raiseInvalidRegex", "re.nim");
	e = (tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ*)0;
	nimln_(50, "re.nim");
	e = (tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ*) newObj((&NTI_TzXIVAyhJcYnc0aWQVu3gg_), sizeof(tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ));
	(*e).Sup.Sup.Sup.m_type = (&NTI_umh9boX2MJLOyMwHcR9cwMtQ_);
	nimln_(51, "re.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(msg);
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(52, "re.nim");
	raiseException((Exception*)e, "RegexError");
	popFrame();
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == NIM_NIL))) goto LA3_;
		copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A*, rawCompile_haWBfS5PJ5KixJQ9ccC8t5Q)(NimStringDesc* pattern, int flags) {
	tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* result;
	NCSTRING msg;
	int offset;
	nimfr_("rawCompile", "re.nim");
	result = (tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A*)0;
	nimln_(56, "re.nim");
	msg = "";
	nimln_(57, "re.nim");
	offset = ((int) 0);
	nimln_(58, "re.nim");
	result = Dl_276014_((pattern ? pattern->data : (NCSTRING)""), flags, (&msg), (&offset), NIM_NIL);
	nimln_(59, "re.nim");
	{
		NimStringDesc* T5_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		if (!(result == NIM_NIL)) goto LA3_;
		nimln_(60, "re.nim");
		T5_ = (NimStringDesc*)0;
		T6_ = (NimStringDesc*)0;
		T6_ = cstrToNimstr(msg);
		nimln_(976, "strutils.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = nsuRepeatChar(32, ((NI)chckRange(offset, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		T5_ = rawNewString((T6_ ? T6_->Sup.len : 0) + (pattern ? pattern->Sup.len : 0) + (T7_ ? T7_->Sup.len : 0) + 4);
appendString(T5_, T6_);
appendString(T5_, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_4));
appendString(T5_, pattern);
appendString(T5_, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_4));
appendString(T5_, T7_);
appendString(T5_, ((NimStringDesc*) &TM_EFUBs0zJOEvQ2SEKsixA2w_5));
		raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q(T5_);
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg flags) {
	tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* result;
	nimfr_("re", "re.nim");
	result = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
	nimln_(76, "re.nim");
	result = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*) newObj((&NTI_dkhOdInu11QXB2HnNpgmJQ_), sizeof(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw));
	nimln_(77, "re.nim");
	(*result).h = rawCompile_haWBfS5PJ5KixJQ9ccC8t5Q(s, ((int) ((flags & ~ 16))));
	nimln_(78, "re.nim");
	{
		NCSTRING msg;
		int options;
		int hasJit;
		if (!((flags &(1U<<((NU)(((tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg) 4))&7U)))!=0)) goto LA3_;
		nimln_(79, "re.nim");
		msg = "";
		nimln_(80, "re.nim");
		options = ((int) 0);
		nimln_(81, "re.nim");
		hasJit = ((int) 0);
		nimln_(82, "re.nim");
		{
			int T7_;
			T7_ = (int)0;
			T7_ = Dl_276036_(((int) 9), ((void*) ((&hasJit))));
			if (!(T7_ == ((NI32) 0))) goto LA8_;
			nimln_(83, "re.nim");
			{
				if (!(hasJit == ((NI32) 1))) goto LA12_;
				nimln_(84, "re.nim");
				options = ((int) 1);
			}
			LA12_: ;
		}
		LA8_: ;
		nimln_(85, "re.nim");
		(*result).e = Dl_276163_((*result).h, options, (&msg));
		nimln_(86, "re.nim");
		{
			NimStringDesc* T18_;
			if (!!((msg == 0))) goto LA16_;
			T18_ = (NimStringDesc*)0;
			T18_ = cstrToNimstr(msg);
			raiseInvalidRegex_uBem1bks9b5wqsVked8xr0Q(T18_);
		}
		LA16_: ;
	}
	LA3_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_reInit000)(void) {
	nimfr_("re", "re.nim");
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, stdlib_reDatInit000)(void) {
static TNimNode* TM_EFUBs0zJOEvQ2SEKsixA2w_3[2];
static TNimNode TM_EFUBs0zJOEvQ2SEKsixA2w_0[4];
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.size = sizeof(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw);
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.kind = 18;
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.base = 0;
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.flags = 3;
TM_EFUBs0zJOEvQ2SEKsixA2w_3[0] = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[1];
TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].kind = 1;
TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].offset = offsetof(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw, h);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].typ = (&NTI_WH9aVfHDhtZbU6Y5QgauqZQ_);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[1].name = "h";
TM_EFUBs0zJOEvQ2SEKsixA2w_3[1] = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[2];
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].kind = 1;
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].offset = offsetof(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw, e);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].typ = (&NTI_z1uZWlkSdiDfd9ahW9a6Ibug_);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[2].name = "e";
TM_EFUBs0zJOEvQ2SEKsixA2w_0[0].len = 2; TM_EFUBs0zJOEvQ2SEKsixA2w_0[0].kind = 2; TM_EFUBs0zJOEvQ2SEKsixA2w_0[0].sons = &TM_EFUBs0zJOEvQ2SEKsixA2w_3[0];
NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_.node = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[0];
NTI_dkhOdInu11QXB2HnNpgmJQ_.size = sizeof(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*);
NTI_dkhOdInu11QXB2HnNpgmJQ_.kind = 22;
NTI_dkhOdInu11QXB2HnNpgmJQ_.base = (&NTI_jxMAPyr9aBYX9b0g7iZ2E8zw_);
NTI_dkhOdInu11QXB2HnNpgmJQ_.flags = 2;
NTI_dkhOdInu11QXB2HnNpgmJQ_.marker = Marker_tyRef_dkhOdInu11QXB2HnNpgmJQ;
(&NTI_dkhOdInu11QXB2HnNpgmJQ_)->finalizer = (void*)finalizeRegEx_00ANangMP3AvVFMngMDJRQ;
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.size = sizeof(tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ);
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.kind = 17;
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.base = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
TM_EFUBs0zJOEvQ2SEKsixA2w_0[3].len = 0; TM_EFUBs0zJOEvQ2SEKsixA2w_0[3].kind = 2;
NTI_umh9boX2MJLOyMwHcR9cwMtQ_.node = &TM_EFUBs0zJOEvQ2SEKsixA2w_0[3];
NTI_TzXIVAyhJcYnc0aWQVu3gg_.size = sizeof(tyObject_RegexError_umh9boX2MJLOyMwHcR9cwMtQ*);
NTI_TzXIVAyhJcYnc0aWQVu3gg_.kind = 22;
NTI_TzXIVAyhJcYnc0aWQVu3gg_.base = (&NTI_umh9boX2MJLOyMwHcR9cwMtQ_);
NTI_TzXIVAyhJcYnc0aWQVu3gg_.marker = Marker_tyRef_TzXIVAyhJcYnc0aWQVu3gg;
}

